### ISSUE TITLE
obrigado por trazer este jogo incrível, gostaria de relatar falha de imagem, está pedindo suporte msaa

### ISSUE THREAD

**Issue by Sal-gamer** [WeegeeDEVELOPER/uMario-PSVita-Port#2]
could add analog support to move the character?  could add MSAA2X or MSAA4X filter support?  you can see a cutout when entering the plumbing, in the middle of the plumbing to see Mário, and when entering the castle you can see the character disappearing on the edges of the door instead of super in the middle of it.

**Comment by Sal-gamer** [comment]
![2021-11-05-173508](https://user-images.githubusercontent.com/55700359/140576773-bc7b5acf-d273-41b9-a424-40bc95d2374a.jpg)
![2021-11-05-173347](https://user-images.githubusercontent.com/55700359/140576790-d8dbe8f5-984a-44a9-b4ef-021ab40290d9.jpg)

**Comment by Sal-gamer** [comment]
out of nowhere , I became immortal , and at the end of the stage there was a cloud on the ground.

**Comment by WeegeeDEVELOPER** [comment]
I will be looking into this! Thanks for reporting the issue.

**Comment by Sal-gamer** [comment]
besides fixing immortality, cloud, among other things, could you add MSAA2X or MSAA4X filter?

**Comment by WeegeeDEVELOPER** [comment]
I have looked into the invincibility issue, but did not manage to figure out what was causing the issue, as for MSAA filters, I am not sure how to apply these, but I will see what I can do.

**Comment by WeegeeDEVELOPER** [comment]
As for analog support, it currently is not planned.
