### ISSUE TITLE
[RFE] Remap controls

### ISSUE THREAD

**Issue by e-minguez** [WeegeeDEVELOPER/uMario-PSVita-Port#3]
Currently using circle to run is ok but I prefer square. It would be nice to have a way to customize the controller buttons.
Thanks.

**Comment by Sal-gamer** [comment]
besides being able to map the controls, it could have Playstation symbols instead of Letters (symbol ∆ [] O X).  in the configuration menu you have the option to change the control, but it is disabled and does not have the Playstation symbols.

**Comment by WeegeeDEVELOPER** [comment]
Great suggestion and will be looked into!

**Comment by appletv4** [comment]
can you make square run and x jump

**Comment by WeegeeDEVELOPER** [comment]
The control scheme has changed in latest release.
